definitions:
  http.HealthCheckResponse:
    description: Response structure for health check
    properties:
      status:
        description: The status of the health check
        type: string
    type: object
info:
  contact: {}
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Returns the health status of the API.
      produces:
      - application/json
      responses:
        "200":
          description: successful health check response
          schema:
            $ref: '#/definitions/http.HealthCheckResponse'
      summary: Health Check
      tags:
      - health
swagger: "2.0"
