services:
  filebrowser:
    build:
      context: .
      dockerfile: _docker/Dockerfile.slim
      args:
        VERSION: dev
        REVISION: local
    container_name: filebrowser-dev
    ports:
      - "8080:80"
    volumes:
      - ./data:/home/filebrowser/data
      - ./srv:/srv
      - /home/bhuppi/Documents/Testing:/disk_one
      - /home/bhuppi/Documents/Testing2:/disk_two
    environment:
      FILEBROWSER_CONFIG: "data/config.yaml"
      FILEBROWSER_ADMIN_PASSWORD: "change-me"
      TZ: "Asia/Kolkata"
    restart: unless-stopped
