root = "."
tmp_dir = "tmp"

[build]
  pre_cmd = ["go run ./scripts/setup-gofitz-cgo", "go run ./scripts/setup-windows-cgo"]
  cmd = "cmd /c tmp\\windows-air-build.bat"
  entrypoint = "./tmp/filebrowser.exe"
  full_bin = "cmd /c tmp\\windows-air-run.bat"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "internal\\web\\dist", "internal\\web\\embed", "internal\\preview\\testdata", "internal\\preview\\thumbnails", "internal\\preview\\heic", "swagger\\docs"]
  exclude_unchanged = true
  follow_symlink = false
  poll = true
  poll_interval = 1000
  log = "air.log"
  delay = 1000 # ms

[log]
  time = true

[misc]
  clean_on_exit = false
