root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/filebrowser.exe --ldflags=\"-w -s -X 'github.com/gtsteffaniak/filebrowser/backend/common/version.CommitSHA=commitSHA' -X 'github.com/gtsteffaniak/filebrowser/backend/common/version.Version=version'\" ."
  bin = "tmp/filebrowser.exe"
  args_bin = ["-c", "test_config.yaml"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "http\\dist", "http\\embed", "swagger\\docs"]
  exclude_unchanged = true
  follow_symlink = false
  poll = true
  poll_interval = 1000
  log = "air.log"
  delay = 1000 # ms

[log]
  time = true

[misc]
  clean_on_exit = true
