root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/filebrowser.exe --ldflags=\"-w -s -X 'github.com/gtsteffaniak/filebrowser/backend/common/version.CommitSHA=testingCommit' -X 'github.com/gtsteffaniak/filebrowser/backend/common/version.Version=testing'\" ."
  bin = "tmp/filebrowser.exe"
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "http/dist", "http/embed", "swagger/docs"]
  log = "air.log"
  delay = 1000 # ms

[log]
  time = true

[misc]
  clean_on_exit = true
