# .goreleaser.yaml
project_name: filebrowser

builds:
  - ldflags:
      - -s -w
    main: main.go
    binary: filebrowser
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    hooks:
      post:
        # Run UPX for non-Windows binaries
        - goos: darwin
          action: upx {{ .Path }}
        - goos: linux
          action: upx {{ .Path }}
    ignore:
      # Exclude arm6 and arm7 for Windows
      - goos: windows
        goarch: arm
        goarm: 6
      - goos: windows
        goarch: arm
        goarm: 7

archives:
  - name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    format: binary

checksum:
  disable: true
