# .goreleaser.yaml
project_name: filebrowser
version: 2

builds:
  # Build configuration for darwin and linux
  - id: default
    env:
      - CGO_ENABLED=1
    ldflags: &ldflags
      - -s -w -X github.com/gtsteffaniak/filebrowser/backend/common/version.Version={{ .Version }} -X github.com/gtsteffaniak/filebrowser/backend/common/version.CommitSHA={{ .ShortCommit }}
    main: main.go
    binary: filebrowser
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    hooks:
      post:
        - upx {{ .Path }}  # Compress the binary with UPX

  # Build configuration for windows without arm
  - id: windows
    ldflags: *ldflags
    main: main.go
    binary: filebrowser
    goos:
      - windows
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}  # Compress the binary with UPX

  # Build configuration for macos without upx
  - id: macos
    ldflags: *ldflags
    main: main.go
    binary: filebrowser
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

  # Build configuration for freebsd without arm & upx
  - id: freeBSD
    ldflags: *ldflags
    main: main.go
    binary: filebrowser
    goos:
      - freebsd
    goarch:
      - amd64

archives:
  - name_template: >
      {{- if eq .Os "windows" -}}
      {{.ProjectName}}
      {{- else -}}
      {{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{.ProjectName}}
      {{- end -}}
    format: binary

checksum:
  disable: true

