# .goreleaser.yaml
project_name: filebrowser
version: 2

builds:
  # Build configuration for darwin and linux
  - id: default
    ldflags: &ldflags
      - -s -w -X github.com/gtsteffaniak/filebrowser/version.Version={{ .Version }} -X github.com/gtsteffaniak/filebrowser/version.CommitSHA={{ .ShortCommit }}
    main: main.go
    binary: filebrowser
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    hooks:
      post: 
        - upx {{ .Path }}  # Compress the binary with UPX

  # Build configuration for windows without arm
  - id: windows
    ldflags: *ldflags
    main: main.go
    binary: filebrowser
    goos:
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    format: binary

checksum:
  disable: true

