# .goreleaser.yaml
project_name: filebrowser
version: 2

builds:
  # Build configuration for linux amd64
  - id: linux-amd64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-linux-musl
    tags:
      - mupdf
      - musl
    ldflags: &ldflags
      - -s -w -X github.com/gtsteffaniak/filebrowser/backend/common/version.Version=v{{ .Version }} -X github.com/gtsteffaniak/filebrowser/backend/common/version.CommitSHA={{ .ShortCommit }}
    main: main.go
    binary: filebrowser
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}


  # Build configuration for macos without upx
  - id: macos
    ldflags: *ldflags
    main: main.go
    binary: filebrowser
    goos:
      - darwin
    goarch:
      - arm64
      - amd64

archives:
  - name_template: >
      {{- if eq .Os "windows" -}}
      {{.ProjectName}}
      {{- else -}}
      {{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{.ProjectName}}
      {{- end -}}
    formats: [ 'binary' ]

checksum:
  disable: true
