server:
  port: 80
  baseURL:  "/"
  logging:
    - levels: "info|warning|error"
  sources:
    - path: "/srv"
auth:
  key: "change-me-to-a-random-string"
  totpSecret: "change-me-to-another-random-string"
  methods:
    password:
      enabled: true
      minLength: 5
      signup: false
    passkey:
      enabled: false
userDefaults:
  sidebar:
    disableQuickToggles: false            # disable the quick toggles in the sidebar
    hideFileActions: false                # hide the file actions in the sidebar
    disableHideOnPreview: false           # keep sidebar open when previewing files
    sticky: true                          # keep sidebar open when navigating
    hideFiles: false                      # hide files in the sidebar tree navigation, when true, will show only directories
    showTools: true                       # show sidebar links of category "tool"; when false they stay in the list but are hidden in the UI

  listing:
    deleteWithoutConfirming: false        # delete files without confirmation
    dateFormat: false                     # when false, the date is relative, when true, the date is an exact timestamp
    showHidden: false                     # show hidden files in the UI. On windows this includes files starting with a dot and windows hidden files
    quickDownload: false                  # show icon to download in one click
    showSelectMultiple: false             # show select multiple files on desktop
    singleClick: false                    # open directory on single click, also enables middle click to open in new tab
    hideFileExt: ""                       # space separated list of file extensions to hide in UI
    showCopyPath: false                   # show copy path button in the context menu
    deleteAfterArchive: true              # delete source files after successful creation/extraction of archives
    viewMode: "normal"                    # view mode to use: eg. normal, list, grid, or compact
    gallerySize: 3                        # 0-9 - the size of the gallery thumbnails

  preview:
    image: true                           # show thumbnail preview image for image files (defaults to true if not set)
    video: true                           # show thumbnail preview image for video files (defaults to true if not set)
    audio: true                           # show thumbnail preview image for audio files (defaults to true if not set)
    motionVideoPreview: true              # show multiple frames for videos in thumbnail preview when hovering (defaults to true if not set)
    office: true                          # show thumbnail preview image for office files (defaults to true if not set)
    popup: true                           # show larger popup preview when hovering over thumbnail (defaults to true if not set)
    disablePreviewExt: ""                 # space separated list of file extensions to disable preview for
    highQuality: true                     # high quality preview thumbnails
    folder: true                          # show thumbnail preview image for folder files (defaults to true if not set)
    models: true                          # show live thumbnail preview for 3D Models files (defaults to true if not set)

  fileViewer:
    editorQuickSave: false                # show quick save button in editor
    autoplayMedia: true                   # autoplay media files in preview (defaults to true if not set)
    disableViewingExt: ""                 # space separated list of file extensions to disable viewing for
    disableOnlyOfficeExt: ".md .txt .pdf .html .xml"  # list of file extensions to disable onlyoffice editor for
    preferEditorForMarkdown: false        # prefer editor first for markdown files instead of the Markdown Viewer
    debugOffice: false                    # debug onlyoffice editor
    defaultMediaPlayer: false             # disable html5 media player and use the default media player

  search:
    disableOptions: false                 # disable the search options in the search bar

  ui:
    darkMode: true                        # should dark mode be enabled (defaults to true if not set)
    themeColor: "var(--blue)"             # theme color to use: eg. #ff0000, or var(--red), var(--purple), etc
    customTheme: ""                       # Name of theme to use chosen from custom themes config
    locale: "en"                          # language to use: eg. de, en, or fr

  fileLoading:
    maxConcurrentUpload: 10               # maximum number of concurrent uploads
    uploadChunkSizeMb: 10                 # upload chunk size in MB
    downloadChunkSizeMb: 0                # download chunk size in MB (0 = no chunking)

  account:
    permissions:
      api: false                          # allow api access
      admin: false                        # allow admin access
      modify: false                       # allow modifying files
      share: false                        # allow sharing files
      realtime: false                     # allow realtime updates
      delete: false                       # allow deleting files
      create: false                       # allow creating or uploading files
      download: true                      # allow downloading files (defaults to true if not set)
    lockPassword: false                   # disable the user from changing their password
    disableSettings: false                # disable the user from viewing the settings page
    loginMethod: "password"               # login method to use: eg. password, proxy, oidc
    disableUpdateNotifications: false     # disable update notifications banner for admin users
