server:
  port: 80
  baseURL:  "/"
  logging:
    - levels: "info|error|warning|debug"
      apiFilter: 'disabled'
  sources:
    - path: "/srv"
auth:
  methods:
    password:
      enabled: true
      minLength: 5
      signup: false
    passkey:
      enabled: false
