server:
  logging:
    - levels: "info|error|warning|debug"
  sources:
    - path: "../frontend/tests/playwright-files"
      config:
        defaultEnabled: true
        createUserDir: true

frontend:
  name: "Graham's Filebrowser"
  disableDefaultLinks: true
  externalLinks:
    - text: "A playwright test"
      url: "https://playwright.dev/"
      title: "Playwright"
  styling:
    disableEventThemes: true
auth:
  methods:
    password:
      enabled: false
    oidc:
      enabled: true
      createUser: true
      clientId: "vyBrzOmcrU3OokiWEZoObdGBscw0eYPNJauBtOJr"
      clientSecret: "gIMKbkEcckUhlGrnE2Vxi8eZhEcfxQqfwFgM0ATzk4DciHGrW2YRtQfqcpRTsmzrxEETkKvZ8yeK3sfoXnUV1IQTzqK7wxw3lEMtmeXi5clj0h7nH1rVGFq2Q3HL8zUe"
      issuerUrl: "http://localhost:8080"
      adminGroup: "Admins"

userDefaults:
  preview:
    image: true
    popup: true
    video: true
    office: true
    highQuality: true
  darkMode: true
  disableSettings: false
  singleClick: false
  permissions:
    admin: false
    modify: true
    share: false
    api: false
    download: true
    create: true