server:
  port: 80
  baseURL:  "/files/"
  logging:
    - levels: "info|error|debug"
  sources:
    - path: "../frontend/tests/playwright-files"
      name: "exclude"
      config:
        defaultEnabled: true
        conditionals:
          rules:
            - folderPath: "excluded"
            - folderPath: "excludedButVisible"
              viewable: true
    - path: "../frontend/tests/playwright-files2"
      name: "include"
      config:
        defaultEnabled: true
        conditionals:
          rules:
            - includeRootItem: "myfolder"
            - includeRootItem: "subfolderExclusions"
            - filePath: "/subfolderExclusions/exclusionlist.sh"
            - folderPath: "/subfolderExclusions/folderItem"
              viewable: true
            - fileStartsWith: "startsWith"
            - folderEndsWith: "Folder"

auth:
  methods:
    noauth: true
frontend:
  name: "Graham's Filebrowser"
  disableDefaultLinks: true
  externalLinks:
    - text: "A playwright test"
      url: "https://playwright.dev/"
      title: "Playwright"
userDefaults:
  permissions:
   realtime: true

userDefaults:
  preview:
    image: true
    popup: true
    video: true
    office: true
    highQuality: true
  permissions:
    download: true
    create: true