server:
  port: 80
  baseURL:  "/"
  logging:
    - levels: "info|error|debug"
  sources:
    - path: "../frontend/tests/playwright-files"
frontend:
  name: "Graham's Filebrowser"
  disableDefaultLinks: true
  externalLinks:
    - text: "A playwright test"
      url: "https://playwright.dev/"
      title: "Playwright"
userDefaults:
  darkMode: true
  disableSettings: false
  scope: "."
  singleClick: false
  permissions:
    admin: false
    create: false
    rename: false
    modify: false
    delete: false
    share: false
    download: false
