http:
  port: 8080
server:
  logging:
    - levels: "info|error|warning|debug"
      apiFilter: 'disabled'
  sources:
    - path: "../frontend/tests/playwright-files"
      config:
        defaultEnabled: true
        createUserDir: true
        defaultPermissions:
          view: true
          download: true
          modify: true
          create: true

frontend:
  name: "Graham's Filebrowser"
  disableDefaultLinks: true
  externalLinks:
    - text: "A playwright test"
      url: "https://playwright.dev/"
      title: "Playwright"
  styling:
    disableEventThemes: true
auth:
  methods:
    password:
      enabled: false
    jwt:
      enabled: true
      secret: "test-jwt-secret-key-for-development-only-do-not-use-in-production"
      algorithm: "HS256"
      header: "X-JWT-Assertion"
      userIdentifier: "sub"
      groupsClaim: "mygroup"
      adminGroup: "admin"
userDefaults:
  ui:
    darkMode: true
  account:
    disableSettings: false
    permissions:
      share: true
  listing:
    singleClick: false
  preview:
    image: true
    popup: true
    video: true
    office: true
    highQuality: true
