name: main release

on:
  push:
    branches:
      - "main"

jobs:
  push_latest_to_registry:
    name: Push latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: gtstef/filebrowser
      - name: Get latest release tag and commit SHA
        id: get_tag_and_sha
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          latest_commit=$(git rev-list -n 1 $latest_tag)
          echo "latest_tag=${latest_tag}" >> $GITHUB_ENV
          echo "latest_commit=${latest_commit}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          file: ./Dockerfile
          push: true
          tags: 'gtstef/filebrowser:latest'
          labels: ${{ steps.meta.outputs.labels }}