name: main release

on:
  push:
    branches:
      - "main"

jobs:
  test_playwright:
    name: Test Playwright
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - uses: actions/setup-node@v4
      - working-directory: frontend
        run: npm i && npm run build
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - working-directory: backend
        run: go build -o filebrowser .
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./_docker/Dockerfile.playwright-general
          push: false
