FROM gtstef/playwright-base
WORKDIR /app

# Copy setup scripts first to leverage caching
COPY [ "./_docker/src/noauth/", "./" ]

WORKDIR /app/frontend
COPY [ "./frontend/tests", "./tests" ]

WORKDIR /app/backend/
COPY [ "./backend/filebrowser", "./"]
RUN mkdir -p ./http/dist
COPY [ "./backend/http/embed/", "./http/dist/"]

# Run tests
RUN ./filebrowser & sleep 2 && cd ../frontend && npx playwright test
