FROM ghcr.io/gtsteffaniak/playwright-base:chromium
WORKDIR /app

# Copy setup scripts first to leverage caching
COPY [ "./_docker/src/previews/", "./" ]

WORKDIR /app/frontend
COPY [ "./frontend/tests", "./tests" ]

WORKDIR /app/backend/
COPY [ "./backend/filebrowser", "./"]
RUN mkdir -p ./internal/web/dist
COPY [ "./backend/internal/web/embed/", "./internal/web/dist/"]

# Run tests
ENV FILEBROWSER_PLAYWRIGHT_TEST=true
RUN ./filebrowser & sleep 2 && cd ../frontend && npx playwright test