FROM ghcr.io/gtsteffaniak/playwright-base:latest
WORKDIR /app

# Copy setup scripts first to leverage caching
COPY [ "./_docker/src/noauth/", "./" ]

WORKDIR /app/frontend
COPY [ "./frontend/tests", "./tests" ]
COPY [ "./frontend/tests/playwright-files", "./tests/playwright-files2" ]

WORKDIR /app/backend/
COPY [ "./backend/filebrowser", "./"]
RUN mkdir -p ./http/dist
COPY [ "./backend/http/embed/", "./http/dist/"]
